services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: clinicslot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    volumes:
      - .:/app
    working_dir: /app 
    command: python manage.py runserver 0.0.0.0:8000
    container_name: clinicslot_web
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: clinicslot
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
  
  redis:
    image: redis:7
    container_name: clinicslot_redis
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: clinicslot_worker
    command: celery -A config worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      DB_NAME: clinicslot
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      REDIS_HOST: redis

volumes:
  postgres_data: