# Generated by Django 6.0.3 on 2026-04-23 09:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSchedules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_start', models.DateTimeField(blank=True, help_text='Time the booking starts', null=True)),
                ('booking_end', models.DateTimeField(blank=True, help_text='Time the booking ends', null=True)),
                ('status', models.BooleanField(default=True, help_text='Indicates if the booking slot is available or not')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the booking slot is deleted')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Date the record was created')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_schedules',
                'ordering': ['date_created'],
                'permissions': [('schedule_read', 'Can read or view booking schedules'), ('schedule_write', 'Can create/update booking schedules'), ('schedule_update', 'Can confirm booking requests'), ('schedule_delete', 'Can reject booking requests')],
                'get_latest_by': 'date_created',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, help_text='Optional address for the patient', max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Optional phone number', max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Date the record was created')),
                ('token', models.CharField(blank=True, help_text='Token for secure access to request bookings', max_length=255, null=True)),
                ('tenant', models.ForeignKey(help_text='Tenant associated with the patient', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_patients', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_patient',
                'ordering': ['date_created'],
                'permissions': [('patient_invite', 'Can invite patients for bookings'), ('patient_view', 'Can view patient details'), ('patient_edit', 'Can edit patient details')],
                'get_latest_by': 'date_created',
            },
        ),
        migrations.CreateModel(
            name='PatientBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, help_text='Optional description for the patient booking', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Staff notes for the patient booking: confirmed, rejected, rescheduled, etc.', null=True)),
                ('reason', models.CharField(blank=True, help_text='Reason for cancellation or rescheduling', max_length=255, null=True)),
                ('token', models.CharField(blank=True, help_text='Token for secure access to booking details', max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Date the record was created')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed'), ('rescheduled', 'Rescheduled'), ('deleted', 'Deleted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('booking_date', models.ForeignKey(help_text='The booking schedule associated with this patient booking', on_delete=django.db.models.deletion.CASCADE, related_name='patient_booking', to='booking.bookingschedules')),
                ('patient', models.ForeignKey(help_text='The patient associated with this booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.patient')),
            ],
            options={
                'db_table': 'patient_bookings',
                'ordering': ['date_created'],
                'permissions': [('blocks_read', 'Can read or view booking blocks'), ('blocks_write', 'Can create/update booking blocks'), ('requests_confirm', 'Can confirm booking requests'), ('requests_reject', 'Can reject booking requests'), ('requests_cancel', 'Can cancel booking requests'), ('requests_reschedule', 'Can reschedule booking requests')],
                'get_latest_by': 'date_created',
            },
        ),
        migrations.CreateModel(
            name='TenantStaff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, help_text='Optional address for the staff member', max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Optional phone number', max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Date the record was created')),
                ('tenant', models.ForeignKey(help_text='Tenant associated with the staff member', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_staffs', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_staff',
                'ordering': ['date_created'],
                'get_latest_by': 'date_created',
            },
        ),
        migrations.AddIndex(
            model_name='bookingschedules',
            index=models.Index(fields=['status', 'booking_start'], name='patient_sch_status_c9f7fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingschedules',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('booking_start', 'booking_end', 'tenant'), name='unique_active_booking_schedule'),
        ),
    ]
